### ISSUE TITLE
List this library in the Arduino IDE Library Manager

### ISSUE THREAD

**Issue by SeanBannister** [shaggythesheep/arduino-button#12]
The Arduino IDE has a Library Manager making it easy to install and get updates from Libraries. It'd be great if this library and the related libraries were listed in there, it's simple to make this happen there's a quick guide [here](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager).

You may want to consider changing the name from "Button" to something easier to search for like "r89m Button".

**Comment by r89m** [comment]
Done!

https://github.com/arduino/Arduino/issues/4957

Hopefully they should be available soon
