### ISSUE TITLE
Feature Internal button ID

### ISSUE THREAD

**Issue by tablatronix** [shaggythesheep/arduino-button#15]
It would be nice to have some sort of button id to track buttons when using the same event callback for all.

Right now I am tracking all my objects, and then use a btn.is() loop manually to ID them. which is cumbersome.

I thought about getting to the bounce pin, but it was too much effort to mod all 3 libraries or use virtuals, and since events return button classes, pushbutton derives are just as much a pain to get to, unless using templates or some pointers ( I don't know c++ all that well )

I figured just adding an ID setter getter to the button class itself would be the easiest way and `_update_button_state` agnostic

If there is something obvious I am not thinking of, let me know.

**Comment by r89m** [comment]
Hi @tablatronix, thanks for raising this.

Would you mind pasting or linking you're current code / loop - I can't quite get my head around how an ID would simplify things, but I'm happy to be persuaded!

Cheers,

Richard

**Comment by tablatronix** [comment]
heres a simplified version

Imagine though if i wanted to register a bunch of buttons, or dynamically instantiate them, it would be much easier to have them all register the same callbacks, so I have a single handler to maintain, then determine which button was pressed much easier ( say I wanted to create a keyboard without using a matrix or scan etc )

``` C++
/*
 * PushButton example. This shows a basic example of how to register events with a button.
 */

#include <Button.h>
#include <ButtonEventCallback.h>
#include <PushButton.h>
#include <Bounce2.h>    // https://github.com/thomasfredericks/Bounce-Arduino-Wiring

// Create an instance of PushButton reading digital pin 5
PushButton button  = PushButton(0);
PushButton button2 = PushButton(2);

String buttonLabels[2] = {"A","B"};

void setup(){

        // Open up the serial port so that we can write to it
    Serial.begin(115200);

        // Configure the button as you'd like - not necessary if you're happy with the defaults
        button.configureButton(configurePushButton);
        button2.configureButton(configurePushButton);

        // When the button is first pressed, call the function onButtonPressed (further down the page)
        button.onPress(onButtonPressed);
        button2.onPress(onButtonPressed);
        // Once the button has been held for 1 second (1000ms) call onButtonHeld. Call it again every 0.5s (500ms) until it is let go
        button.onHoldRepeat(1000, 500, onButtonHeld);
        button2.onHoldRepeat(1000, 500, onButtonHeld);
        // When the button is released, call onButtonReleased
        button.onRelease(onButtonReleased);
        button2.onRelease(onButtonReleased);
}

void loop(){
    // Check the state of the button
    button.update();
    button2.update();
}

// Use this function to configure the internal Bounce object to suit you. See the documentation at: https://github.com/thomasfredericks/Bounce2/wiki
// This function can be left out if the defaults are acceptable - just don't call configureButton
void configurePushButton(Bounce& bouncedButton){

        // Set the debounce interval to 15ms - default is 10ms
        bouncedButton.interval(15);
}

int getButtonID(Button& btn){
    if(btn.is(button)) return 0;
    if(btn.is(button2)) return 1;
}

// btn is a reference to the button that fired the event. That means you can use the same event handler for many buttons
void onButtonPressed(Button& btn){
    int buttonid = getButtonID(btn);
    Serial.println("Button " + buttonLabels[buttonid] + " pressed");
}

// duration reports back how long it has been since the button was originally pressed.
// repeatCount tells us how many times this function has been called by this button.
void onButtonHeld(Button& btn, uint16_t duration, uint16_t repeatCount){
    int buttonid = getButtonID(btn);
    Serial.print("Button " + buttonLabels[buttonid] + " has been held for ");
    Serial.print(duration);
    Serial.print(" ms; this event has been fired ");
    Serial.print(repeatCount);
    Serial.println(" times");
}

// duration reports back the total time that the button was held down
void onButtonReleased(Button& btn, uint16_t duration){
    int buttonid = getButtonID(btn);
    Serial.print("Button " + buttonLabels[buttonid] + " released after ");
    Serial.print(duration);
    Serial.println(" ms");
}
```

**Comment by r89m** [comment]
Thanks Shawn. 

I'm just headed to the pub now but will take a look at it over the weekend.

**Comment by tablatronix** [comment]
cheers

It is not a huge deal, I would have to keep an array to do the updates for all the buttons anyway.
an alternative would be adding arbitrary arguments to the event class callbacks, more code investment, but supports more use cases..

**Comment by r89m** [comment]
Hi Shawn,

I'm a little torn. I actually think the way you are currently doing it is correct.

Anyway, I have put together a new branch though, which adds the ability specify metadata for each button. In it's default state, this gives you the ability to differentiate between 256 buttons (which should hopefully be enough!)

The new branch can be found here:
https://github.com/r89m/Button/tree/metadata-support

All you need to do is download it as a zip and copy it over your existing library.

I've update the SimpleBasicButton example to show the usage, but essentially there are two new methods: setMetadata and getMetadata. These methods take / return a byte. I considered adding the metadata as one of the constructor arguments but I fear it would make the constructors fairly unwieldy with the additional parameters.

Let me know if that helps you out

Richard

**Comment by tablatronix** [comment]
Im sure that would be sufficient, a byte gets you a ton of button Ids and overhead to save states and actual meta using a mask.

**Comment by tablatronix** [comment]
yup works well

**Comment by tablatronix** [comment]
I think this is light weight enough to merge into master. Either way closing issue.
