### ISSUE TITLE
How to manage with NC (Normally Close) button

### ISSUE THREAD

**Issue by CrNMGuy** [shaggythesheep/arduino-button#19]
Hi, 

Sorry for posting on Issues

I'm using your librairy, works like a charm !
Now, I'm stuck on an other type of push button : a NC one
this mean when not pushed, circuit is close, and when pushed, circuit is open

I parse source files, but didn't see an obvious way to fork them
Would you recommand any way ?

Thanks !

**Comment by CrNMGuy** [comment]
Too quick ! 

Here's how to manage NC button : 

On the PushButton library, invert the value of button state : 
```
boolean PushButton::_update_button_state(){
	
	// Update the button
	bouncer.update();
	// Return whether it is pressed or not
	return (bouncer.read() == !_button_pressed_value);
}
```

**Comment by CrNMGuy** [comment]
But this way, you can't make NC and NO at the same time
Looking for a way to fork PushButton...

**Comment by CrNMGuy** [comment]
Found ! 
How to bring the new PushButtonNC to the project ?

**Comment by r89m** [comment]
Hi!

Glad you're finding it useful and managing to navigate the code okay! 

I think PushButton actually already supoorts what you're after!

Try using 
PushButton(PIN, PRESSED_WHEN_LOW)

**Comment by CrNMGuy** [comment]
LOW / HIGH is about connected to GND / VCC if i'm right

Here, it's about been connected to something or not
which i think is different.

**Comment by r89m** [comment]
You probably don't want your input connected to nothing as you'll get random noise causing phantom presses (you might want to have a Google about pull / pull down resistors) 

What you would probably want is the pin pulled pulled up using something like a 10k resistor with the switch connected to ground. In its default state it would read LOW but when it is pressed it would read HIGH.

I hope that makes sense. I'm about to get on with the flight now so unfortunately won't be able to reply for a while.

**Comment by CrNMGuy** [comment]
You are right, i think the wrong way on my circuit
Will do a button with pullup resistor and your initial code will work fine !

Thanks
