### ISSUE TITLE
Fix for category warning

### ISSUE THREAD

**Issue by SeanBannister** [shaggythesheep/arduino-button#8]
When using this in the Arduino IDE 1.6.8 I was getting the following warning:
`WARNING: Category 'Input/Output' in library Buttons is not valid. Setting to 'Uncategorized'`

I fixed this by changing [Line 7 of library.properties](https://github.com/r89m/arduino-button/blob/master/library.properties#L7) from:
`category=Input/Output`
to
`category=Signal Input/Output`

**Comment by r89m** [comment]
Thanks Sean, will fix this. Sorry about the delay replying, I need to sort out my notifications!
