### ISSUE TITLE
Can't use the library in the Arduino IDE with the current directory structure

### ISSUE THREAD

**Issue by SeanBannister** [shaggythesheep/arduino-button#9]
Currently the project has .h and .cpp files in sub directories. The Arduino IDE can't compile files in sub directories unless its in a directory called utility. It'd be great if this library could support the Arduino IDE to encourage adoption. I'm rather interested in contributing to it.

**Comment by ivankravets** [comment]
@SeanBannister You can try temporary [PlatformIO IDE](http://platformio.org/platformio-ide) and http://platformio.org/lib/show/444/Buttons (where this library works).

**Comment by r89m** [comment]
Hi Sean, thanks for reporting this. I'll take a look at resolving the issue.

@ivankravets Thanks for the help you offered Sean. With regards to a fix, I'm planing on moving the sub folders into a src directory - would that be compatible with PlatformIO?

**Comment by ivankravets** [comment]
@r89m PlatformIO has very flexible own Build System. We don't force developers to keep files in repo using specific rules (like Arduino does). Developers write code and using `include` and `exclude` fields from [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html) decide which source code should be included in the final library. 

If you move all folders to the `src` directory, then users will use like `#include <Button/ButtonEventCallback.h>`

**Comment by r89m** [comment]
Thanks Ivan.

@SeanBannister Sooo.. as with anything Arduino related that took a little bit longer than intended! What I have done is left this project as a Base Library with a very simple BasicButton available for use. 
However I strongly recommend that you do not use BasicButton by itelsf and instead use this library as well as one of the new libraries linked to in the README file (PushButton, CapacitiveButton etc.)

These libraries will need to be downloaded and installed into the Arduino library folder, as well as any dependencies that they mention in their own READMEs.

Sorry for not testing it on a fresh system, I totally forgot that I'd been using symlinks to get it to work on my PC!

Anyway, let me know if that works for you or if you need any more explanation.#

Cheers,

Richard

**Comment by SeanBannister** [comment]
Thanks a heap @r89m that works great :)
